# Generated by Django 5.0.4 on 2024-05-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
