# Generated by Django 5.0.4 on 2024-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
