# Generated by Django 5.0.4 on 2024-05-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('avatar', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('monitor', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
            ],
        ),
    ]
